# WIE KANN ICH EINZELNE PROZESSSCHRITTE WENIGER OFT LAUFEN LASSEN?

# run the process 100 times
amount: 100

# start at the create_order step
initial: create_product

steps:
  create_product:
    generate: Product
    next: create_customer
  create_customer:
    generate: Customer
    next: create_order
  create_order:
    # generate one Order 100% of the time
    generate: Order
    next: create_invoice
  create_invoice:
    generate:
      # generate an Invoice 95% of the time, otherwise don't generate anything
      Invoice: 0.95

schemas:
  Invoice:
    # reference to another schema
    customer: Customer
    order: Order
    date:
      type: date
      # must not be earlier than the date in order
      min: $order.date
      max: 2021-12-31

  Order:
    customer: Customer
    # WIE KANN ICH MEHRERE PRODUKTE ZU EINER ORDER HINZUFÜGEN?
    product: Product
    amount:
      type: number
      min: 2
      max: 4
    date:
      type: date
      min: 2021-12-20
      max: 2021-12-31

  Customer:
    name:
      type: string_from_file
      source: C:\Programmieren\sledo\examples\order-invoice\customerNames.txt
    country:
      type: string_from_file
      source: C:\Programmieren\sledo\examples\order-invoice\countries.txt

    # SOLLTEN PREIS; PRODUKT UND PRODUKTNUMMER ZUSAMMENGEHÖREN? (KEINE DOPPLUNGEN IN ANDEREN KOMBIS?)
  Product:
    name:
      type: string_from_file
      source: C:\Programmieren\sledo\examples\order-invoice\productNames.txt
    price:
      type: number
      min: 0
      max: 999
      digits: 2
