# run the process 100 times
amount: 100

# start at the create_product step
initial: create_product

steps:
  create_order:
    # generate one Order 100% of the time
    generate: Order
    next: create_invoice
  create_invoice:
    generate:
      # generate an Invoice 95% of the time, otherwise don't generate anything
      Invoice: 0.95

schemas:
    Invoice:
        # reference to another schema
        order: Order
        date:
            type: date
            # must not be earlier than the date in order
            min: $order.date
            max: 2021-12-31

    Order:
        amount:
            type: number
            min: 2
            max: 4
        date:
            type: date
            min: 2021-12-20
            max: 2021-12-31
    products: List

  Product:
    name:
      type: name
    number:
      type: number
      # should have 4 digits
      min: 1000
      max: 9999
    price:
      type: number
      min: 0.00
      max: 99999.99
      # should not have more than 2 digits after comma
      digits: 2

  Customer:
    name:
      type: name
    country:
      type:
